jobs:
- deployment: VMDeploy
  displayName: web
  pool:
    vmImage: 'Ubuntu-latest'
  environment:
    name: newvm
    resourceType: VirtualMachine
  strategy:
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment